# Generated by Django 2.0 on 2018-01-11 16:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CentralNode',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_ip', models.GenericIPAddressField()),
                ('node_local_lat', models.FloatField(default=0)),
                ('node_local_long', models.FloatField(default=0)),
                ('node_local_alt', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('dayplan_id', models.AutoField(primary_key=True, serialize=False)),
                ('dayplan_gen_time', models.DateTimeField(auto_now=True)),
                ('dayplan_time', models.DateTimeField()),
                ('dayplan_water_qtd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddedSystem',
            fields=[
                ('esys_id', models.AutoField(primary_key=True, serialize=False)),
                ('esys_local_lat', models.FloatField(default=0)),
                ('esys_local_long', models.FloatField(default=0)),
                ('esys_local_alt', models.FloatField(default=0)),
                ('esys_state', models.IntegerField()),
                ('esys_name', models.CharField(default='', max_length=30)),
                ('esys_network_pass', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationTime',
            fields=[
                ('irrigation_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('irrigation_time_date', models.DateTimeField()),
                ('irrigation_time_qtd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('plant_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('prop_name', models.CharField(max_length=50)),
                ('prop_description', models.CharField(max_length=250)),
                ('prop_address', models.CharField(max_length=100)),
                ('prop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('read_id', models.AutoField(primary_key=True, serialize=False)),
                ('read_timestamp', models.DateTimeField(auto_now=True)),
                ('read_value', models.IntegerField()),
                ('read_dayplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_dayplan', to='api.DayPlan')),
            ],
        ),
        migrations.CreateModel(
            name='ReadType',
            fields=[
                ('read_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('read_type_name', models.CharField(max_length=50)),
                ('read_type_units', models.CharField(max_length=3)),
                ('read_type_coef', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_name', models.CharField(default='sensor nr x', max_length=50)),
                ('sensor_state', models.IntegerField()),
                ('sensor_timerate', models.IntegerField()),
                ('sensor_depth', models.IntegerField()),
                ('sensor_esys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_embsys', to='api.EmbeddedSystem')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('sensor_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('space_id', models.AutoField(primary_key=True, serialize=False)),
                ('space_name', models.CharField(max_length=50)),
                ('space_description', models.CharField(max_length=150)),
                ('space_irrigation_hour', models.IntegerField()),
                ('space_plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_plant_type', to='api.PlantType')),
                ('space_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_property', to='api.Property')),
            ],
        ),
        migrations.CreateModel(
            name='SubSpace',
            fields=[
                ('sub', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50)),
                ('sub_description', models.CharField(max_length=150)),
                ('sub_space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_space', to='api.Space')),
            ],
        ),
        migrations.CreateModel(
            name='TimeRestriction',
            fields=[
                ('time_restriction_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_restriction_begin', models.DateTimeField()),
                ('time_restriction_end', models.DateTimeField()),
                ('time_restriction_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_spaceid', to='api.Space')),
            ],
        ),
        migrations.CreateModel(
            name='UserManagesProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop', to='api.Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('warning_id', models.AutoField(primary_key=True, serialize=False)),
                ('warning_description', models.CharField(max_length=300)),
                ('warning_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refer_property', to='api.Property')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_type', to='api.SensorType'),
        ),
        migrations.AddField(
            model_name='readtype',
            name='read_type_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_belongs_to', to='api.Sensor'),
        ),
        migrations.AddField(
            model_name='read',
            name='read_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_sensor', to='api.Sensor'),
        ),
        migrations.AddField(
            model_name='read',
            name='read_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_readtype', to='api.ReadType'),
        ),
        migrations.AddField(
            model_name='irrigationtime',
            name='irrigation_time_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refers_to', to='api.SubSpace'),
        ),
        migrations.AddField(
            model_name='embeddedsystem',
            name='esys_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_sub', to='api.SubSpace'),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='dayplan_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_subspace', to='api.SubSpace'),
        ),
        migrations.AddField(
            model_name='centralnode',
            name='node_property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Property'),
        ),
        migrations.AddField(
            model_name='user',
            name='props',
            field=models.ManyToManyField(through='api.UserManagesProperty', to='api.Property'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='usermanagesproperty',
            unique_together={('user', 'prop')},
        ),
    ]
