# Generated by Django 2.0 on 2018-01-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subspace',
            old_name='sub',
            new_name='sub_id',
        ),
    ]
