# Generated by Django 2.0 on 2018-01-19 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180111_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralnode',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='readtype',
            name='read_type_sensor',
        ),
        migrations.AlterField(
            model_name='centralnode',
            name='node_property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Property'),
        ),
    ]
