# Generated by Django 2.0 on 2018-01-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180119_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embeddedsystem',
            name='esys_network_pass',
        ),
        migrations.AddField(
            model_name='centralnode',
            name='node_network_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='centralnode',
            name='node_network_pass',
            field=models.CharField(default='', max_length=30),
        ),
    ]
