# Generated by Django 2.0 on 2018-01-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180119_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centralnode',
            old_name='node_network_pass',
            new_name='node_network_password',
        ),
    ]
