# Generated by Django 2.0 on 2018-01-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180119_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigationtime',
            old_name='irrigation_time_qtd',
            new_name='irrigation_time_qty',
        ),
        migrations.AddField(
            model_name='irrigationtime',
            name='irrigation_time_qty_unit',
            field=models.CharField(default='L', max_length=10),
        ),
    ]
