# Generated by Django 2.0 on 2018-01-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180121_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayplan',
            old_name='dayplan_water_qtd',
            new_name='dayplan_water_qty',
        ),
        migrations.AddField(
            model_name='dayplan',
            name='dayplan_water_qty_unit',
            field=models.CharField(default='L', max_length=10),
        ),
    ]
