# Generated by Django 2.0 on 2018-01-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_setup_data_sensor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planttype',
            name='plant_type_name',
        ),
        migrations.AddField(
            model_name='planttype',
            name='plant_type_name_eng',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AddField(
            model_name='planttype',
            name='plant_type_name_por',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='planttype',
            name='plant_type_id',
            field=models.CharField(max_length=65, primary_key=True, serialize=False),
        ),
    ]
