# Generated by Django 2.0 on 2018-01-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_setup_data_plant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_depth_unit',
            field=models.CharField(default='cm', max_length=6),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_timerate_unit',
            field=models.CharField(default='min', max_length=6),
        ),
    ]
