# Generated by Django 2.0 on 2018-01-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180129_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_state',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_last_read',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
