# Generated by Django 2.0 on 2018-01-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180129_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='dayplan_rain',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='dayplan_rain_unit',
            field=models.CharField(default='cm3', max_length=6),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='dayplan_water_qty_unit',
            field=models.CharField(default='L', max_length=6),
        ),
    ]
