# Generated by Django 2.0 on 2018-01-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180131_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='dayplan_rain_unit',
            field=models.CharField(default='mm', max_length=6),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='dayplan_water_qty_unit',
            field=models.CharField(default='mm', max_length=6),
        ),
    ]
