# Generated by Django 2.0 on 2018-01-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180131_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='subspace',
            name='sub_area',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='subspace',
            name='sub_area_unit',
            field=models.CharField(default='m2', max_length=6),
        ),
        migrations.AlterField(
            model_name='irrigationtime',
            name='irrigation_time_qty_unit',
            field=models.CharField(default='mm', max_length=10),
        ),
    ]
