# Generated by Django 2.0 on 2018-01-31 18:21

import api.models.reads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180131_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='read_value',
            field=models.FloatField(validators=[api.models.reads.validate_read]),
        ),
    ]
