# Generated by Django 2.0 on 2017-12-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='dayplan_gen_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='dayplan_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='irrigationtime',
            name='irrigation_time_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='read',
            name='read_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
