# Generated by Django 2.0 on 2018-01-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180119_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='read',
            name='read_dayplan',
        ),
    ]
