# Generated by Django 2.0 on 2017-12-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171221_2344'),
        ('api', '0004_auto_20171222_0100'),
    ]

    operations = [
    ]
