# Generated by Django 2.0 on 2018-01-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_read_read_dayplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='dayplan_water_qtd',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='irrigationtime',
            name='irrigation_time_qtd',
            field=models.FloatField(),
        ),
    ]
