# Generated by Django 2.0 on 2017-12-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20171223_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralnode',
            name='node_property',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Property'),
            preserve_default=False,
        ),
    ]
