# Generated by Django 2.0 on 2017-12-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_centralnode_node_property'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userhasproperty',
            unique_together={('user_has_id', 'prop_has_id')},
        ),
    ]
