# Generated by Django 2.0 on 2018-01-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180119_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='read_value',
            field=models.FloatField(),
        ),
    ]
