# Generated by Django 2.0 on 2017-12-27 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171226_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagesProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop', to='api.Property')),
            ],
        ),
        migrations.RenameModel(
            old_name='Warnings',
            new_name='Warning',
        ),
        migrations.AlterUniqueTogether(
            name='userhasproperty',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userhasproperty',
            name='prop_has_id',
        ),
        migrations.RemoveField(
            model_name='userhasproperty',
            name='user_has_id',
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='dayplan_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_subspace', to='api.SubSpace'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_esys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to_embsys', to='api.EmbeddedSystem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='props',
            field=models.ManyToManyField(through='api.UserManagesProperty', to='api.Property'),
        ),
        migrations.DeleteModel(
            name='UserHasProperty',
        ),
        migrations.AddField(
            model_name='usermanagesproperty',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usermanagesproperty',
            unique_together={('user_id', 'prop_id')},
        ),
    ]
