# Generated by Django 2.0 on 2017-12-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171227_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddedsystem',
            name='esys_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='embeddedsystem',
            name='esys_network_pass',
            field=models.CharField(default='', max_length=30),
        ),
    ]
