# Generated by Django 2.0 on 2018-01-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171229_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralnode',
            name='node_local',
        ),
        migrations.RemoveField(
            model_name='embeddedsystem',
            name='esys_local',
        ),
        migrations.AddField(
            model_name='centralnode',
            name='node_local_alt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='centralnode',
            name='node_local_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='centralnode',
            name='node_local_long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='embeddedsystem',
            name='esys_local_alt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='embeddedsystem',
            name='esys_local_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='embeddedsystem',
            name='esys_local_long',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Localization',
        ),
    ]
