# Generated by Django 2.0 on 2018-01-03 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180103_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanagesproperty',
            old_name='prop_id',
            new_name='prop',
        ),
        migrations.RenameField(
            model_name='usermanagesproperty',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usermanagesproperty',
            unique_together={('user', 'prop')},
        ),
    ]
