# Generated by Django 2.0 on 2018-01-08 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180103_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='warning_property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='refer_property', to='api.Property'),
            preserve_default=False,
        ),
    ]
