# Generated by Django 2.0 on 2018-01-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_warning_warning_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_name',
            field=models.CharField(default='sensor nr x', max_length=50),
        ),
    ]
