# Generated by Django 2.0 on 2018-01-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sensor_sensor_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeRestrition',
            new_name='TimeRestriction',
        ),
        migrations.RenameField(
            model_name='timerestriction',
            old_name='time_restrition_id',
            new_name='time_restriction_id',
        ),
        migrations.RenameField(
            model_name='timerestriction',
            old_name='time_restrition_space',
            new_name='time_restriction_space',
        ),
    ]
