# Generated by Django 2.0 on 2018-01-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180111_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timerestriction',
            old_name='time_begin',
            new_name='time_restriction_begin',
        ),
        migrations.RenameField(
            model_name='timerestriction',
            old_name='time_duration',
            new_name='time_restriction_end',
        ),
    ]
